name: Dev Branch Pipeline

on:
  push:
    branches:
      - main

env:
  RUNNER_SWITCH: ${{ github.ref == 'refs/heads/dev' && vars.RUNNER_SWITCH_DEV || github.ref == 'refs/heads/qa' && vars.RUNNER_SWITCH_QA || github.ref == 'refs/heads/uat' && vars.RUNNER_SWITCH_UAT || github.ref == 'refs/heads/main' && vars.RUNNER_SWITCH_PROD }}  # Set to 'OFF' to use shared runner
  RUNS_ON: ${{ vars.RUNNER_SWITCH == 'ON' && 'self-hosted' || 'ubuntu-latest' }}  # Set to 'OFF' to use shared runner #Add these line                   

jobs:
  build:
    runs-on: ${{vars.RUNS_ON}} #add these line 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Step
        run: echo "1st job running succesfull"

      - name: Build Step
        run: echo ${{env.RUNS_ON}}

  
